// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package invdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const commitReservedStock = `-- name: CommitReservedStock :execrows
UPDATE inventory
SET reserved = reserved - $2, updated_at = now()
WHERE variant_id = $1 AND reserved >= $2
`

type CommitReservedStockParams struct {
	VariantID uuid.UUID `json:"variant_id"`
	Reserved  int32     `json:"reserved"`
}

// 提交(支付成功):reserved--(available 已在预留时扣减)。
func (q *Queries) CommitReservedStock(ctx context.Context, arg CommitReservedStockParams) (int64, error) {
	result, err := q.db.Exec(ctx, commitReservedStock, arg.VariantID, arg.Reserved)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countLedgerByKind = `-- name: CountLedgerByKind :one
SELECT COUNT(*)::bigint FROM stock_ledger WHERE variant_id = $1 AND kind = $2
`

type CountLedgerByKindParams struct {
	VariantID uuid.UUID `json:"variant_id"`
	Kind      string    `json:"kind"`
}

func (q *Queries) CountLedgerByKind(ctx context.Context, arg CountLedgerByKindParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLedgerByKind, arg.VariantID, arg.Kind)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createReservation = `-- name: CreateReservation :one
INSERT INTO reservations (order_id, variant_id, qty, status, expires_at)
VALUES ($1, $2, $3, 'held', $4)
RETURNING id, order_id, variant_id, qty, status, expires_at, created_at, updated_at
`

type CreateReservationParams struct {
	OrderID   pgtype.UUID `json:"order_id"`
	VariantID uuid.UUID   `json:"variant_id"`
	Qty       int32       `json:"qty"`
	ExpiresAt time.Time   `json:"expires_at"`
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, createReservation,
		arg.OrderID,
		arg.VariantID,
		arg.Qty,
		arg.ExpiresAt,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.VariantID,
		&i.Qty,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensureInventoryRow = `-- name: EnsureInventoryRow :exec
INSERT INTO inventory (variant_id, available, reserved) VALUES ($1, 0, 0)
ON CONFLICT (variant_id) DO NOTHING
`

// 新建规格时建空库存行(available 0)。
func (q *Queries) EnsureInventoryRow(ctx context.Context, variantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, ensureInventoryRow, variantID)
	return err
}

const getInventory = `-- name: GetInventory :one
SELECT variant_id, available, reserved, updated_at
FROM inventory WHERE variant_id = $1
`

func (q *Queries) GetInventory(ctx context.Context, variantID uuid.UUID) (Inventory, error) {
	row := q.db.QueryRow(ctx, getInventory, variantID)
	var i Inventory
	err := row.Scan(
		&i.VariantID,
		&i.Available,
		&i.Reserved,
		&i.UpdatedAt,
	)
	return i, err
}

const getReservation = `-- name: GetReservation :one
SELECT id, order_id, variant_id, qty, status, expires_at, created_at, updated_at
FROM reservations WHERE id = $1
`

func (q *Queries) GetReservation(ctx context.Context, id uuid.UUID) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservation, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.VariantID,
		&i.Qty,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertLedger = `-- name: InsertLedger :exec
INSERT INTO stock_ledger (variant_id, delta_available, delta_reserved, kind, reservation_id)
VALUES ($1, $2, $3, $4, $5)
`

type InsertLedgerParams struct {
	VariantID      uuid.UUID   `json:"variant_id"`
	DeltaAvailable int32       `json:"delta_available"`
	DeltaReserved  int32       `json:"delta_reserved"`
	Kind           string      `json:"kind"`
	ReservationID  pgtype.UUID `json:"reservation_id"`
}

func (q *Queries) InsertLedger(ctx context.Context, arg InsertLedgerParams) error {
	_, err := q.db.Exec(ctx, insertLedger,
		arg.VariantID,
		arg.DeltaAvailable,
		arg.DeltaReserved,
		arg.Kind,
		arg.ReservationID,
	)
	return err
}

const listExpiredHeldReservations = `-- name: ListExpiredHeldReservations :many
SELECT id, order_id, variant_id, qty, status, expires_at, created_at, updated_at
FROM reservations
WHERE status = 'held' AND expires_at < now()
ORDER BY expires_at
LIMIT $1
`

func (q *Queries) ListExpiredHeldReservations(ctx context.Context, limit int32) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, listExpiredHeldReservations, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reservation
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.VariantID,
			&i.Qty,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationsByOrder = `-- name: ListReservationsByOrder :many
SELECT id, order_id, variant_id, qty, status, expires_at, created_at, updated_at
FROM reservations WHERE order_id = $1 ORDER BY created_at
`

func (q *Queries) ListReservationsByOrder(ctx context.Context, orderID pgtype.UUID) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, listReservationsByOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reservation
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.VariantID,
			&i.Qty,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReservation = `-- name: MarkReservation :execrows
UPDATE reservations
SET status = $2, updated_at = now()
WHERE id = $1 AND status = 'held'
`

type MarkReservationParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

// 状态机迁移仅当当前为 held(防 sweeper/webhook 竞争,先到者赢)。返回受影响行数。
func (q *Queries) MarkReservation(ctx context.Context, arg MarkReservationParams) (int64, error) {
	result, err := q.db.Exec(ctx, markReservation, arg.ID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reconcileLedger = `-- name: ReconcileLedger :one
SELECT
    COALESCE(SUM(delta_available), 0)::bigint AS sum_available,
    COALESCE(SUM(delta_reserved), 0)::bigint  AS sum_reserved,
    COUNT(*)::bigint                          AS entries
FROM stock_ledger WHERE variant_id = $1
`

type ReconcileLedgerRow struct {
	SumAvailable int64 `json:"sum_available"`
	SumReserved  int64 `json:"sum_reserved"`
	Entries      int64 `json:"entries"`
}

// 台账对账:每个 variant 的 delta 累计应等于库存净变化(SPEC §7 验证)。
func (q *Queries) ReconcileLedger(ctx context.Context, variantID uuid.UUID) (ReconcileLedgerRow, error) {
	row := q.db.QueryRow(ctx, reconcileLedger, variantID)
	var i ReconcileLedgerRow
	err := row.Scan(&i.SumAvailable, &i.SumReserved, &i.Entries)
	return i, err
}

const releaseReservedStock = `-- name: ReleaseReservedStock :execrows
UPDATE inventory
SET available = available + $2,
    reserved  = reserved - $2,
    updated_at = now()
WHERE variant_id = $1 AND reserved >= $2
`

type ReleaseReservedStockParams struct {
	VariantID uuid.UUID `json:"variant_id"`
	Available int32     `json:"available"`
}

// 释放(取消/超时):available++, reserved--。
func (q *Queries) ReleaseReservedStock(ctx context.Context, arg ReleaseReservedStockParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseReservedStock, arg.VariantID, arg.Available)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restockStock = `-- name: RestockStock :execrows
INSERT INTO inventory (variant_id, available, reserved) VALUES ($1, $2, 0)
ON CONFLICT (variant_id) DO UPDATE
    SET available = inventory.available + EXCLUDED.available, updated_at = now()
`

type RestockStockParams struct {
	VariantID uuid.UUID `json:"variant_id"`
	Available int32     `json:"available"`
}

// 补货(admin):available += qty。库存行不存在则建之(新规格首次补货)。
func (q *Queries) RestockStock(ctx context.Context, arg RestockStockParams) (int64, error) {
	result, err := q.db.Exec(ctx, restockStock, arg.VariantID, arg.Available)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setInventory = `-- name: SetInventory :exec
UPDATE inventory SET available = $2, reserved = $3, updated_at = now()
WHERE variant_id = $1
`

type SetInventoryParams struct {
	VariantID uuid.UUID `json:"variant_id"`
	Available int32     `json:"available"`
	Reserved  int32     `json:"reserved"`
}

// 测试夹具/初始化:直接设定库存计数。
func (q *Queries) SetInventory(ctx context.Context, arg SetInventoryParams) error {
	_, err := q.db.Exec(ctx, setInventory, arg.VariantID, arg.Available, arg.Reserved)
	return err
}

const tryReserveStock = `-- name: TryReserveStock :execrows

UPDATE inventory
SET available = available - $2,
    reserved  = reserved + $2,
    updated_at = now()
WHERE variant_id = $1 AND available >= $2
`

type TryReserveStockParams struct {
	VariantID uuid.UUID `json:"variant_id"`
	Available int32     `json:"available"`
}

// 库存预留引擎(SPEC §7 招牌)。一律参数化;原子条件更新用 :execrows 检查受影响行数。
// 防超卖核心:available>=qty 才扣减(隐式行锁,READ COMMITTED 下正确)。
// 返回受影响行数:==1 成功,==0 库存不足。
func (q *Queries) TryReserveStock(ctx context.Context, arg TryReserveStockParams) (int64, error) {
	result, err := q.db.Exec(ctx, tryReserveStock, arg.VariantID, arg.Available)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
