// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package invdb

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	pgvector "github.com/pgvector/pgvector-go"
)

type Cart struct {
	ID        uuid.UUID `json:"id"`
	UserID    *string   `json:"user_id"`
	Status    string    `json:"status"`
	Currency  string    `json:"currency"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type CartItem struct {
	ID        uuid.UUID `json:"id"`
	CartID    uuid.UUID `json:"cart_id"`
	VariantID uuid.UUID `json:"variant_id"`
	Qty       int32     `json:"qty"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ConsumedEvent struct {
	Consumer  string    `json:"consumer"`
	EventID   string    `json:"event_id"`
	CreatedAt time.Time `json:"created_at"`
}

type DeadLetter struct {
	ID        int64           `json:"id"`
	Consumer  string          `json:"consumer"`
	EventID   string          `json:"event_id"`
	Subject   string          `json:"subject"`
	EventType string          `json:"event_type"`
	Payload   json.RawMessage `json:"payload"`
	Error     string          `json:"error"`
	Attempts  int32           `json:"attempts"`
	CreatedAt time.Time       `json:"created_at"`
}

type Inventory struct {
	VariantID uuid.UUID `json:"variant_id"`
	Available int32     `json:"available"`
	Reserved  int32     `json:"reserved"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Order struct {
	ID                    uuid.UUID   `json:"id"`
	UserID                string      `json:"user_id"`
	CartID                pgtype.UUID `json:"cart_id"`
	Status                string      `json:"status"`
	Currency              string      `json:"currency"`
	SubtotalCents         int64       `json:"subtotal_cents"`
	TotalCents            int64       `json:"total_cents"`
	IdempotencyKey        string      `json:"idempotency_key"`
	PaymentProvider       string      `json:"payment_provider"`
	PaymentStatus         string      `json:"payment_status"`
	StripePaymentIntentID *string     `json:"stripe_payment_intent_id"`
	ClientSecret          *string     `json:"client_secret"`
	CreatedAt             time.Time   `json:"created_at"`
	UpdatedAt             time.Time   `json:"updated_at"`
}

type OrderItem struct {
	ID             uuid.UUID `json:"id"`
	OrderID        uuid.UUID `json:"order_id"`
	VariantID      uuid.UUID `json:"variant_id"`
	Sku            string    `json:"sku"`
	Name           string    `json:"name"`
	UnitPriceCents int64     `json:"unit_price_cents"`
	Qty            int32     `json:"qty"`
	LineTotalCents int64     `json:"line_total_cents"`
	CreatedAt      time.Time `json:"created_at"`
}

type Outbox struct {
	ID            int64              `json:"id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   uuid.UUID          `json:"aggregate_id"`
	EventType     string             `json:"event_type"`
	Payload       json.RawMessage    `json:"payload"`
	CreatedAt     time.Time          `json:"created_at"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	TraceParent   string             `json:"trace_parent"`
}

type ProcessedEvent struct {
	EventID   string    `json:"event_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Product struct {
	ID            uuid.UUID       `json:"id"`
	Slug          string          `json:"slug"`
	ProductTypeID uuid.UUID       `json:"product_type_id"`
	Name          string          `json:"name"`
	Description   string          `json:"description"`
	Status        string          `json:"status"`
	Attributes    json.RawMessage `json:"attributes"`
	ImageUrl      string          `json:"image_url"`
	Embedding     pgvector.Vector `json:"embedding"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

type ProductType struct {
	ID              uuid.UUID       `json:"id"`
	Key             string          `json:"key"`
	Name            string          `json:"name"`
	AttributeSchema json.RawMessage `json:"attribute_schema"`
	CreatedAt       time.Time       `json:"created_at"`
}

type Reservation struct {
	ID        uuid.UUID   `json:"id"`
	OrderID   pgtype.UUID `json:"order_id"`
	VariantID uuid.UUID   `json:"variant_id"`
	Qty       int32       `json:"qty"`
	Status    string      `json:"status"`
	ExpiresAt time.Time   `json:"expires_at"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type StockLedger struct {
	ID             int64       `json:"id"`
	VariantID      uuid.UUID   `json:"variant_id"`
	DeltaAvailable int32       `json:"delta_available"`
	DeltaReserved  int32       `json:"delta_reserved"`
	Kind           string      `json:"kind"`
	ReservationID  pgtype.UUID `json:"reservation_id"`
	CreatedAt      time.Time   `json:"created_at"`
}

type Variant struct {
	ID         uuid.UUID       `json:"id"`
	ProductID  uuid.UUID       `json:"product_id"`
	Sku        string          `json:"sku"`
	Name       string          `json:"name"`
	PriceCents int64           `json:"price_cents"`
	Currency   string          `json:"currency"`
	Attributes json.RawMessage `json:"attributes"`
	Status     string          `json:"status"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
}
