// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package catalogdb

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const countProducts = `-- name: CountProducts :one
SELECT COUNT(DISTINCT p.id)::bigint AS total
FROM products p
JOIN product_types pt ON pt.id = p.product_type_id
WHERE p.status = 'active'
  AND ($1::text IS NULL OR pt.key = $1)
  AND ($2::text IS NULL OR p.name ILIKE '%' || $2 || '%')
`

type CountProductsParams struct {
	TypeKey *string `json:"type_key"`
	Q       *string `json:"q"`
}

func (q *Queries) CountProducts(ctx context.Context, arg CountProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts, arg.TypeKey, arg.Q)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT
    p.id,
    p.slug,
    p.name,
    p.description,
    pt.key AS type,
    p.attributes
FROM products p
JOIN product_types pt ON pt.id = p.product_type_id
WHERE p.slug = $1 AND p.status = 'active'
`

type GetProductBySlugRow struct {
	ID          uuid.UUID       `json:"id"`
	Slug        string          `json:"slug"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Type        string          `json:"type"`
	Attributes  json.RawMessage `json:"attributes"`
}

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (GetProductBySlugRow, error) {
	row := q.db.QueryRow(ctx, getProductBySlug, slug)
	var i GetProductBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Attributes,
	)
	return i, err
}

const listProductTypes = `-- name: ListProductTypes :many

SELECT id, key, name, attribute_schema, created_at
FROM product_types
ORDER BY name
`

// 商品目录查询(sqlc)。一律参数化;不在查询中 SELECT embedding(避免 pgx 需注册 vector 类型)。
func (q *Queries) ListProductTypes(ctx context.Context) ([]ProductType, error) {
	rows, err := q.db.Query(ctx, listProductTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductType
	for rows.Next() {
		var i ProductType
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.AttributeSchema,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT
    p.slug,
    p.name,
    pt.key AS type,
    p.attributes,
    p.image_url,
    COALESCE(MIN(v.price_cents), 0)::bigint AS price_from_cents,
    COALESCE(MIN(v.currency), 'USD')::text  AS currency
FROM products p
JOIN product_types pt ON pt.id = p.product_type_id
LEFT JOIN variants v ON v.product_id = p.id AND v.status = 'active'
WHERE p.status = 'active'
  AND ($3::text IS NULL OR pt.key = $3)
  AND ($4::text IS NULL OR p.name ILIKE '%' || $4 || '%')
GROUP BY p.id, pt.key
ORDER BY
    CASE WHEN $5::text = 'price_asc'  THEN MIN(v.price_cents) END ASC,
    CASE WHEN $5::text = 'price_desc' THEN MIN(v.price_cents) END DESC,
    CASE WHEN $5::text = 'name'       THEN p.name END ASC,
    p.created_at DESC
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit   int32   `json:"limit"`
	Offset  int32   `json:"offset"`
	TypeKey *string `json:"type_key"`
	Q       *string `json:"q"`
	Sort    string  `json:"sort"`
}

type ListProductsRow struct {
	Slug           string          `json:"slug"`
	Name           string          `json:"name"`
	Type           string          `json:"type"`
	Attributes     json.RawMessage `json:"attributes"`
	ImageUrl       string          `json:"image_url"`
	PriceFromCents int64           `json:"price_from_cents"`
	Currency       string          `json:"currency"`
}

// 列表 + 过滤 + 分页 + 多种排序(单查询经 CASE 驱动 ORDER BY)。
// price_from_cents = 该款 active 规格的最低价;currency 取对应币种。
func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.Limit,
		arg.Offset,
		arg.TypeKey,
		arg.Q,
		arg.Sort,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.Slug,
			&i.Name,
			&i.Type,
			&i.Attributes,
			&i.ImageUrl,
			&i.PriceFromCents,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantsByProductID = `-- name: ListVariantsByProductID :many
SELECT
    v.id,
    v.sku,
    v.name,
    v.price_cents,
    v.currency,
    v.attributes,
    COALESCE(inv.available, 0)::int AS available
FROM variants v
LEFT JOIN inventory inv ON inv.variant_id = v.id
WHERE v.product_id = $1 AND v.status = 'active'
ORDER BY v.price_cents
`

type ListVariantsByProductIDRow struct {
	ID         uuid.UUID       `json:"id"`
	Sku        string          `json:"sku"`
	Name       string          `json:"name"`
	PriceCents int64           `json:"price_cents"`
	Currency   string          `json:"currency"`
	Attributes json.RawMessage `json:"attributes"`
	Available  int32           `json:"available"`
}

// available = inventory.available(可售量,契约 §9.3);无库存行视为 0。
func (q *Queries) ListVariantsByProductID(ctx context.Context, productID uuid.UUID) ([]ListVariantsByProductIDRow, error) {
	rows, err := q.db.Query(ctx, listVariantsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVariantsByProductIDRow
	for rows.Next() {
		var i ListVariantsByProductIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.PriceCents,
			&i.Currency,
			&i.Attributes,
			&i.Available,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
