// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package catalogdb

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	pgvector "github.com/pgvector/pgvector-go"
)

type Inventory struct {
	VariantID uuid.UUID `json:"variant_id"`
	Available int32     `json:"available"`
	Reserved  int32     `json:"reserved"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Product struct {
	ID            uuid.UUID       `json:"id"`
	Slug          string          `json:"slug"`
	ProductTypeID uuid.UUID       `json:"product_type_id"`
	Name          string          `json:"name"`
	Description   string          `json:"description"`
	Status        string          `json:"status"`
	Attributes    json.RawMessage `json:"attributes"`
	ImageUrl      string          `json:"image_url"`
	Embedding     pgvector.Vector `json:"embedding"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

type ProductType struct {
	ID              uuid.UUID       `json:"id"`
	Key             string          `json:"key"`
	Name            string          `json:"name"`
	AttributeSchema json.RawMessage `json:"attribute_schema"`
	CreatedAt       time.Time       `json:"created_at"`
}

type Variant struct {
	ID         uuid.UUID       `json:"id"`
	ProductID  uuid.UUID       `json:"product_id"`
	Sku        string          `json:"sku"`
	Name       string          `json:"name"`
	PriceCents int64           `json:"price_cents"`
	Currency   string          `json:"currency"`
	Attributes json.RawMessage `json:"attributes"`
	Status     string          `json:"status"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
}
