// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package admindb

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const adminArchiveProduct = `-- name: AdminArchiveProduct :execrows
UPDATE products SET status = 'archived', updated_at = now() WHERE id = $1
`

func (q *Queries) AdminArchiveProduct(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, adminArchiveProduct, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminCountInventory = `-- name: AdminCountInventory :one
SELECT COUNT(*)::bigint
FROM variants v
LEFT JOIN inventory inv ON inv.variant_id = v.id
WHERE ($1::bool = false OR COALESCE(inv.available, 0) <= $2::int)
`

type AdminCountInventoryParams struct {
	Low       bool  `json:"low"`
	Threshold int32 `json:"threshold"`
}

func (q *Queries) AdminCountInventory(ctx context.Context, arg AdminCountInventoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountInventory, arg.Low, arg.Threshold)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const adminCountOrders = `-- name: AdminCountOrders :one
SELECT COUNT(*)::bigint FROM orders
WHERE ($1::text IS NULL OR status = $1)
`

func (q *Queries) AdminCountOrders(ctx context.Context, status *string) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountOrders, status)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const adminCountProducts = `-- name: AdminCountProducts :one
SELECT COUNT(*)::bigint FROM products p
WHERE ($1::text IS NULL OR p.name ILIKE '%' || $1 || '%')
  AND ($2::text IS NULL OR p.status = $2)
`

type AdminCountProductsParams struct {
	Q      *string `json:"q"`
	Status *string `json:"status"`
}

func (q *Queries) AdminCountProducts(ctx context.Context, arg AdminCountProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountProducts, arg.Q, arg.Status)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const adminCountStockLedger = `-- name: AdminCountStockLedger :one
SELECT COUNT(*)::bigint FROM stock_ledger WHERE variant_id = $1
`

func (q *Queries) AdminCountStockLedger(ctx context.Context, variantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountStockLedger, variantID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const adminCreateProduct = `-- name: AdminCreateProduct :one
INSERT INTO products (slug, product_type_id, name, description, status, attributes, image_url)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, slug, name, description, status, attributes, image_url
`

type AdminCreateProductParams struct {
	Slug          string          `json:"slug"`
	ProductTypeID uuid.UUID       `json:"product_type_id"`
	Name          string          `json:"name"`
	Description   string          `json:"description"`
	Status        string          `json:"status"`
	Attributes    json.RawMessage `json:"attributes"`
	ImageUrl      string          `json:"image_url"`
}

type AdminCreateProductRow struct {
	ID          uuid.UUID       `json:"id"`
	Slug        string          `json:"slug"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Status      string          `json:"status"`
	Attributes  json.RawMessage `json:"attributes"`
	ImageUrl    string          `json:"image_url"`
}

func (q *Queries) AdminCreateProduct(ctx context.Context, arg AdminCreateProductParams) (AdminCreateProductRow, error) {
	row := q.db.QueryRow(ctx, adminCreateProduct,
		arg.Slug,
		arg.ProductTypeID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Attributes,
		arg.ImageUrl,
	)
	var i AdminCreateProductRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Attributes,
		&i.ImageUrl,
	)
	return i, err
}

const adminCreateVariant = `-- name: AdminCreateVariant :one
INSERT INTO variants (product_id, sku, name, price_cents, currency, attributes, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, product_id, sku, name, price_cents, currency, attributes, status
`

type AdminCreateVariantParams struct {
	ProductID  uuid.UUID       `json:"product_id"`
	Sku        string          `json:"sku"`
	Name       string          `json:"name"`
	PriceCents int64           `json:"price_cents"`
	Currency   string          `json:"currency"`
	Attributes json.RawMessage `json:"attributes"`
	Status     string          `json:"status"`
}

type AdminCreateVariantRow struct {
	ID         uuid.UUID       `json:"id"`
	ProductID  uuid.UUID       `json:"product_id"`
	Sku        string          `json:"sku"`
	Name       string          `json:"name"`
	PriceCents int64           `json:"price_cents"`
	Currency   string          `json:"currency"`
	Attributes json.RawMessage `json:"attributes"`
	Status     string          `json:"status"`
}

func (q *Queries) AdminCreateVariant(ctx context.Context, arg AdminCreateVariantParams) (AdminCreateVariantRow, error) {
	row := q.db.QueryRow(ctx, adminCreateVariant,
		arg.ProductID,
		arg.Sku,
		arg.Name,
		arg.PriceCents,
		arg.Currency,
		arg.Attributes,
		arg.Status,
	)
	var i AdminCreateVariantRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.Name,
		&i.PriceCents,
		&i.Currency,
		&i.Attributes,
		&i.Status,
	)
	return i, err
}

const adminGetProduct = `-- name: AdminGetProduct :one
SELECT p.id, p.slug, p.name, p.description, pt.key AS type, p.status, p.attributes, p.image_url
FROM products p JOIN product_types pt ON pt.id = p.product_type_id
WHERE p.id = $1
`

type AdminGetProductRow struct {
	ID          uuid.UUID       `json:"id"`
	Slug        string          `json:"slug"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Type        string          `json:"type"`
	Status      string          `json:"status"`
	Attributes  json.RawMessage `json:"attributes"`
	ImageUrl    string          `json:"image_url"`
}

func (q *Queries) AdminGetProduct(ctx context.Context, id uuid.UUID) (AdminGetProductRow, error) {
	row := q.db.QueryRow(ctx, adminGetProduct, id)
	var i AdminGetProductRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.Attributes,
		&i.ImageUrl,
	)
	return i, err
}

const adminGetVariant = `-- name: AdminGetVariant :one
SELECT id, product_id, sku, name, price_cents, currency, attributes, status
FROM variants WHERE id = $1
`

type AdminGetVariantRow struct {
	ID         uuid.UUID       `json:"id"`
	ProductID  uuid.UUID       `json:"product_id"`
	Sku        string          `json:"sku"`
	Name       string          `json:"name"`
	PriceCents int64           `json:"price_cents"`
	Currency   string          `json:"currency"`
	Attributes json.RawMessage `json:"attributes"`
	Status     string          `json:"status"`
}

func (q *Queries) AdminGetVariant(ctx context.Context, id uuid.UUID) (AdminGetVariantRow, error) {
	row := q.db.QueryRow(ctx, adminGetVariant, id)
	var i AdminGetVariantRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.Name,
		&i.PriceCents,
		&i.Currency,
		&i.Attributes,
		&i.Status,
	)
	return i, err
}

const adminListInventory = `-- name: AdminListInventory :many
SELECT
    v.id AS variant_id, v.sku, p.name AS product_name,
    COALESCE(inv.available, 0)::int AS available,
    COALESCE(inv.reserved, 0)::int  AS reserved
FROM variants v
JOIN products p ON p.id = v.product_id
LEFT JOIN inventory inv ON inv.variant_id = v.id
WHERE ($1::bool = false OR COALESCE(inv.available, 0) <= $2::int)
ORDER BY COALESCE(inv.available, 0) ASC, v.sku
LIMIT $4 OFFSET $3
`

type AdminListInventoryParams struct {
	Low       bool  `json:"low"`
	Threshold int32 `json:"threshold"`
	Off       int32 `json:"off"`
	Lim       int32 `json:"lim"`
}

type AdminListInventoryRow struct {
	VariantID   uuid.UUID `json:"variant_id"`
	Sku         string    `json:"sku"`
	ProductName string    `json:"product_name"`
	Available   int32     `json:"available"`
	Reserved    int32     `json:"reserved"`
}

func (q *Queries) AdminListInventory(ctx context.Context, arg AdminListInventoryParams) ([]AdminListInventoryRow, error) {
	rows, err := q.db.Query(ctx, adminListInventory,
		arg.Low,
		arg.Threshold,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListInventoryRow
	for rows.Next() {
		var i AdminListInventoryRow
		if err := rows.Scan(
			&i.VariantID,
			&i.Sku,
			&i.ProductName,
			&i.Available,
			&i.Reserved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListOrders = `-- name: AdminListOrders :many
SELECT o.id, o.user_id, o.status, o.total_cents, o.currency, o.created_at,
       COALESCE(SUM(oi.qty), 0)::bigint AS item_count
FROM orders o
LEFT JOIN order_items oi ON oi.order_id = o.id
WHERE ($1::text IS NULL OR o.status = $1)
GROUP BY o.id
ORDER BY o.created_at DESC
LIMIT $3 OFFSET $2
`

type AdminListOrdersParams struct {
	Status *string `json:"status"`
	Off    int32   `json:"off"`
	Lim    int32   `json:"lim"`
}

type AdminListOrdersRow struct {
	ID         uuid.UUID `json:"id"`
	UserID     string    `json:"user_id"`
	Status     string    `json:"status"`
	TotalCents int64     `json:"total_cents"`
	Currency   string    `json:"currency"`
	CreatedAt  time.Time `json:"created_at"`
	ItemCount  int64     `json:"item_count"`
}

func (q *Queries) AdminListOrders(ctx context.Context, arg AdminListOrdersParams) ([]AdminListOrdersRow, error) {
	rows, err := q.db.Query(ctx, adminListOrders, arg.Status, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListOrdersRow
	for rows.Next() {
		var i AdminListOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.TotalCents,
			&i.Currency,
			&i.CreatedAt,
			&i.ItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListProducts = `-- name: AdminListProducts :many
SELECT
    p.id, p.slug, p.name, pt.key AS type, p.status,
    COUNT(DISTINCT v.id)::bigint              AS variant_count,
    COALESCE(MIN(v.price_cents), 0)::bigint   AS price_min_cents,
    COALESCE(MAX(v.price_cents), 0)::bigint   AS price_max_cents,
    COALESCE(SUM(inv.available), 0)::bigint   AS total_available
FROM products p
JOIN product_types pt ON pt.id = p.product_type_id
LEFT JOIN variants v  ON v.product_id = p.id
LEFT JOIN inventory inv ON inv.variant_id = v.id
WHERE ($1::text IS NULL OR p.name ILIKE '%' || $1 || '%')
  AND ($2::text IS NULL OR p.status = $2)
GROUP BY p.id, pt.key
ORDER BY p.created_at DESC
LIMIT $4 OFFSET $3
`

type AdminListProductsParams struct {
	Q      *string `json:"q"`
	Status *string `json:"status"`
	Off    int32   `json:"off"`
	Lim    int32   `json:"lim"`
}

type AdminListProductsRow struct {
	ID             uuid.UUID `json:"id"`
	Slug           string    `json:"slug"`
	Name           string    `json:"name"`
	Type           string    `json:"type"`
	Status         string    `json:"status"`
	VariantCount   int64     `json:"variant_count"`
	PriceMinCents  int64     `json:"price_min_cents"`
	PriceMaxCents  int64     `json:"price_max_cents"`
	TotalAvailable int64     `json:"total_available"`
}

func (q *Queries) AdminListProducts(ctx context.Context, arg AdminListProductsParams) ([]AdminListProductsRow, error) {
	rows, err := q.db.Query(ctx, adminListProducts,
		arg.Q,
		arg.Status,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListProductsRow
	for rows.Next() {
		var i AdminListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Type,
			&i.Status,
			&i.VariantCount,
			&i.PriceMinCents,
			&i.PriceMaxCents,
			&i.TotalAvailable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListStockLedger = `-- name: AdminListStockLedger :many
SELECT id, variant_id, delta_available, delta_reserved, kind, reservation_id, created_at
FROM stock_ledger WHERE variant_id = $1
ORDER BY id DESC
LIMIT $3 OFFSET $2
`

type AdminListStockLedgerParams struct {
	VariantID uuid.UUID `json:"variant_id"`
	Off       int32     `json:"off"`
	Lim       int32     `json:"lim"`
}

func (q *Queries) AdminListStockLedger(ctx context.Context, arg AdminListStockLedgerParams) ([]StockLedger, error) {
	rows, err := q.db.Query(ctx, adminListStockLedger, arg.VariantID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockLedger
	for rows.Next() {
		var i StockLedger
		if err := rows.Scan(
			&i.ID,
			&i.VariantID,
			&i.DeltaAvailable,
			&i.DeltaReserved,
			&i.Kind,
			&i.ReservationID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminUpdateProduct = `-- name: AdminUpdateProduct :one
UPDATE products
SET slug = $2, name = $3, description = $4, status = $5, attributes = $6, image_url = $7, updated_at = now()
WHERE id = $1
RETURNING id, slug, name, description, status, attributes, image_url
`

type AdminUpdateProductParams struct {
	ID          uuid.UUID       `json:"id"`
	Slug        string          `json:"slug"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Status      string          `json:"status"`
	Attributes  json.RawMessage `json:"attributes"`
	ImageUrl    string          `json:"image_url"`
}

type AdminUpdateProductRow struct {
	ID          uuid.UUID       `json:"id"`
	Slug        string          `json:"slug"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Status      string          `json:"status"`
	Attributes  json.RawMessage `json:"attributes"`
	ImageUrl    string          `json:"image_url"`
}

func (q *Queries) AdminUpdateProduct(ctx context.Context, arg AdminUpdateProductParams) (AdminUpdateProductRow, error) {
	row := q.db.QueryRow(ctx, adminUpdateProduct,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Attributes,
		arg.ImageUrl,
	)
	var i AdminUpdateProductRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Attributes,
		&i.ImageUrl,
	)
	return i, err
}

const adminUpdateVariant = `-- name: AdminUpdateVariant :one
UPDATE variants
SET sku = $2, name = $3, price_cents = $4, currency = $5, attributes = $6, status = $7, updated_at = now()
WHERE id = $1
RETURNING id, product_id, sku, name, price_cents, currency, attributes, status
`

type AdminUpdateVariantParams struct {
	ID         uuid.UUID       `json:"id"`
	Sku        string          `json:"sku"`
	Name       string          `json:"name"`
	PriceCents int64           `json:"price_cents"`
	Currency   string          `json:"currency"`
	Attributes json.RawMessage `json:"attributes"`
	Status     string          `json:"status"`
}

type AdminUpdateVariantRow struct {
	ID         uuid.UUID       `json:"id"`
	ProductID  uuid.UUID       `json:"product_id"`
	Sku        string          `json:"sku"`
	Name       string          `json:"name"`
	PriceCents int64           `json:"price_cents"`
	Currency   string          `json:"currency"`
	Attributes json.RawMessage `json:"attributes"`
	Status     string          `json:"status"`
}

func (q *Queries) AdminUpdateVariant(ctx context.Context, arg AdminUpdateVariantParams) (AdminUpdateVariantRow, error) {
	row := q.db.QueryRow(ctx, adminUpdateVariant,
		arg.ID,
		arg.Sku,
		arg.Name,
		arg.PriceCents,
		arg.Currency,
		arg.Attributes,
		arg.Status,
	)
	var i AdminUpdateVariantRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.Name,
		&i.PriceCents,
		&i.Currency,
		&i.Attributes,
		&i.Status,
	)
	return i, err
}

const getProductTypeByKey = `-- name: GetProductTypeByKey :one

SELECT id, key, name, attribute_schema FROM product_types WHERE key = $1
`

type GetProductTypeByKeyRow struct {
	ID              uuid.UUID       `json:"id"`
	Key             string          `json:"key"`
	Name            string          `json:"name"`
	AttributeSchema json.RawMessage `json:"attribute_schema"`
}

// 管理后台查询(契约 §9.5)。一律参数化;金额 *_cents bigint;状态枚举 + CHECK。
func (q *Queries) GetProductTypeByKey(ctx context.Context, key string) (GetProductTypeByKeyRow, error) {
	row := q.db.QueryRow(ctx, getProductTypeByKey, key)
	var i GetProductTypeByKeyRow
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.AttributeSchema,
	)
	return i, err
}

const listProductsForIndex = `-- name: ListProductsForIndex :many
SELECT id, name, description, attributes FROM products WHERE status = 'active' ORDER BY created_at
`

type ListProductsForIndexRow struct {
	ID          uuid.UUID       `json:"id"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Attributes  json.RawMessage `json:"attributes"`
}

// 搜索 backfill:取所有 active 商品的可索引文本来源。
func (q *Queries) ListProductsForIndex(ctx context.Context) ([]ListProductsForIndexRow, error) {
	rows, err := q.db.Query(ctx, listProductsForIndex)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsForIndexRow
	for rows.Next() {
		var i ListProductsForIndexRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Attributes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
