// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cart.sql

package cartdb

import (
	"context"

	"github.com/google/uuid"
)

const createCart = `-- name: CreateCart :one

INSERT INTO carts (user_id, currency) VALUES ($1, $2)
RETURNING id, user_id, status, currency, created_at, updated_at
`

type CreateCartParams struct {
	UserID   *string `json:"user_id"`
	Currency string  `json:"currency"`
}

// 购物车查询。增删改后由 service 重新读取「最新购物车整体」(契约 §9.4)。
func (q *Queries) CreateCart(ctx context.Context, arg CreateCartParams) (Cart, error) {
	row := q.db.QueryRow(ctx, createCart, arg.UserID, arg.Currency)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCartItem = `-- name: DeleteCartItem :execrows
DELETE FROM cart_items WHERE id = $1 AND cart_id = $2
`

type DeleteCartItemParams struct {
	ID     uuid.UUID `json:"id"`
	CartID uuid.UUID `json:"cart_id"`
}

func (q *Queries) DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCartItem, arg.ID, arg.CartID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveCartByUser = `-- name: GetActiveCartByUser :one
SELECT id, user_id, status, currency, created_at, updated_at
FROM carts WHERE user_id = $1 AND status = 'active'
`

func (q *Queries) GetActiveCartByUser(ctx context.Context, userID *string) (Cart, error) {
	row := q.db.QueryRow(ctx, getActiveCartByUser, userID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCart = `-- name: GetCart :one
SELECT id, user_id, status, currency, created_at, updated_at
FROM carts WHERE id = $1
`

func (q *Queries) GetCart(ctx context.Context, id uuid.UUID) (Cart, error) {
	row := q.db.QueryRow(ctx, getCart, id)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartItem = `-- name: GetCartItem :one
SELECT id, cart_id, variant_id, qty, created_at, updated_at
FROM cart_items WHERE id = $1
`

func (q *Queries) GetCartItem(ctx context.Context, id uuid.UUID) (CartItem, error) {
	row := q.db.QueryRow(ctx, getCartItem, id)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.VariantID,
		&i.Qty,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCartItemsDetailed = `-- name: ListCartItemsDetailed :many
SELECT
    ci.id,
    ci.variant_id,
    ci.qty,
    v.sku,
    v.price_cents AS unit_price_cents,
    v.currency,
    (p.name || ' · ' || v.name)::text AS name,
    COALESCE(inv.available, 0)::int AS available
FROM cart_items ci
JOIN variants v ON v.id = ci.variant_id
JOIN products p ON p.id = v.product_id
LEFT JOIN inventory inv ON inv.variant_id = ci.variant_id
WHERE ci.cart_id = $1
ORDER BY ci.created_at
`

type ListCartItemsDetailedRow struct {
	ID             uuid.UUID `json:"id"`
	VariantID      uuid.UUID `json:"variant_id"`
	Qty            int32     `json:"qty"`
	Sku            string    `json:"sku"`
	UnitPriceCents int64     `json:"unit_price_cents"`
	Currency       string    `json:"currency"`
	Name           string    `json:"name"`
	Available      int32     `json:"available"`
}

// 明细 + 商品/规格快照 + 可售量(契约 §9.4 的 cart item 形状)。
func (q *Queries) ListCartItemsDetailed(ctx context.Context, cartID uuid.UUID) ([]ListCartItemsDetailedRow, error) {
	rows, err := q.db.Query(ctx, listCartItemsDetailed, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCartItemsDetailedRow
	for rows.Next() {
		var i ListCartItemsDetailedRow
		if err := rows.Scan(
			&i.ID,
			&i.VariantID,
			&i.Qty,
			&i.Sku,
			&i.UnitPriceCents,
			&i.Currency,
			&i.Name,
			&i.Available,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCartConverted = `-- name: MarkCartConverted :exec
UPDATE carts SET status = 'converted', updated_at = now() WHERE id = $1
`

func (q *Queries) MarkCartConverted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markCartConverted, id)
	return err
}

const touchCart = `-- name: TouchCart :exec
UPDATE carts SET updated_at = now() WHERE id = $1
`

func (q *Queries) TouchCart(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchCart, id)
	return err
}

const updateCartItemQty = `-- name: UpdateCartItemQty :one
UPDATE cart_items SET qty = $2, updated_at = now() WHERE id = $1
RETURNING id, cart_id, variant_id, qty, created_at, updated_at
`

type UpdateCartItemQtyParams struct {
	ID  uuid.UUID `json:"id"`
	Qty int32     `json:"qty"`
}

func (q *Queries) UpdateCartItemQty(ctx context.Context, arg UpdateCartItemQtyParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, updateCartItemQty, arg.ID, arg.Qty)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.VariantID,
		&i.Qty,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCartItem = `-- name: UpsertCartItem :one
INSERT INTO cart_items (cart_id, variant_id, qty) VALUES ($1, $2, $3)
ON CONFLICT (cart_id, variant_id)
DO UPDATE SET qty = cart_items.qty + EXCLUDED.qty, updated_at = now()
RETURNING id, cart_id, variant_id, qty, created_at, updated_at
`

type UpsertCartItemParams struct {
	CartID    uuid.UUID `json:"cart_id"`
	VariantID uuid.UUID `json:"variant_id"`
	Qty       int32     `json:"qty"`
}

// 加项:同 variant 已存在则累加数量。
func (q *Queries) UpsertCartItem(ctx context.Context, arg UpsertCartItemParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, upsertCartItem, arg.CartID, arg.VariantID, arg.Qty)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.VariantID,
		&i.Qty,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
