// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order.sql

package orderdb

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countOrdersByUser = `-- name: CountOrdersByUser :one
SELECT COUNT(*)::bigint FROM orders WHERE user_id = $1
`

func (q *Queries) CountOrdersByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countOrdersByUser, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countOutbox = `-- name: CountOutbox :one
SELECT COUNT(*)::bigint FROM outbox WHERE aggregate_id = $1 AND event_type = $2
`

type CountOutboxParams struct {
	AggregateID uuid.UUID `json:"aggregate_id"`
	EventType   string    `json:"event_type"`
}

func (q *Queries) CountOutbox(ctx context.Context, arg CountOutboxParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOutbox, arg.AggregateID, arg.EventType)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createOrder = `-- name: CreateOrder :one

INSERT INTO orders (user_id, cart_id, currency, subtotal_cents, total_cents, idempotency_key)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, cart_id, status, currency, subtotal_cents, total_cents,
          idempotency_key, payment_provider, payment_status, stripe_payment_intent_id,
          client_secret, created_at, updated_at
`

type CreateOrderParams struct {
	UserID         string      `json:"user_id"`
	CartID         pgtype.UUID `json:"cart_id"`
	Currency       string      `json:"currency"`
	SubtotalCents  int64       `json:"subtotal_cents"`
	TotalCents     int64       `json:"total_cents"`
	IdempotencyKey string      `json:"idempotency_key"`
}

// 订单 / 订单项(快照)/ 幂等去重 / outbox 查询。
func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.UserID,
		arg.CartID,
		arg.Currency,
		arg.SubtotalCents,
		arg.TotalCents,
		arg.IdempotencyKey,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CartID,
		&i.Status,
		&i.Currency,
		&i.SubtotalCents,
		&i.TotalCents,
		&i.IdempotencyKey,
		&i.PaymentProvider,
		&i.PaymentStatus,
		&i.StripePaymentIntentID,
		&i.ClientSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :exec
INSERT INTO order_items (order_id, variant_id, sku, name, unit_price_cents, qty, line_total_cents)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateOrderItemParams struct {
	OrderID        uuid.UUID `json:"order_id"`
	VariantID      uuid.UUID `json:"variant_id"`
	Sku            string    `json:"sku"`
	Name           string    `json:"name"`
	UnitPriceCents int64     `json:"unit_price_cents"`
	Qty            int32     `json:"qty"`
	LineTotalCents int64     `json:"line_total_cents"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error {
	_, err := q.db.Exec(ctx, createOrderItem,
		arg.OrderID,
		arg.VariantID,
		arg.Sku,
		arg.Name,
		arg.UnitPriceCents,
		arg.Qty,
		arg.LineTotalCents,
	)
	return err
}

const getOrder = `-- name: GetOrder :one
SELECT id, user_id, cart_id, status, currency, subtotal_cents, total_cents,
       idempotency_key, payment_provider, payment_status, stripe_payment_intent_id,
       client_secret, created_at, updated_at
FROM orders WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CartID,
		&i.Status,
		&i.Currency,
		&i.SubtotalCents,
		&i.TotalCents,
		&i.IdempotencyKey,
		&i.PaymentProvider,
		&i.PaymentStatus,
		&i.StripePaymentIntentID,
		&i.ClientSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByIdempotencyKey = `-- name: GetOrderByIdempotencyKey :one
SELECT id, user_id, cart_id, status, currency, subtotal_cents, total_cents,
       idempotency_key, payment_provider, payment_status, stripe_payment_intent_id,
       client_secret, created_at, updated_at
FROM orders WHERE user_id = $1 AND idempotency_key = $2
`

type GetOrderByIdempotencyKeyParams struct {
	UserID         string `json:"user_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

// 幂等键按用户作用域,防止跨用户串单。
func (q *Queries) GetOrderByIdempotencyKey(ctx context.Context, arg GetOrderByIdempotencyKeyParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByIdempotencyKey, arg.UserID, arg.IdempotencyKey)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CartID,
		&i.Status,
		&i.Currency,
		&i.SubtotalCents,
		&i.TotalCents,
		&i.IdempotencyKey,
		&i.PaymentProvider,
		&i.PaymentStatus,
		&i.StripePaymentIntentID,
		&i.ClientSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByPaymentIntent = `-- name: GetOrderByPaymentIntent :one
SELECT id, user_id, cart_id, status, currency, subtotal_cents, total_cents,
       idempotency_key, payment_provider, payment_status, stripe_payment_intent_id,
       client_secret, created_at, updated_at
FROM orders WHERE stripe_payment_intent_id = $1
`

func (q *Queries) GetOrderByPaymentIntent(ctx context.Context, stripePaymentIntentID *string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByPaymentIntent, stripePaymentIntentID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CartID,
		&i.Status,
		&i.Currency,
		&i.SubtotalCents,
		&i.TotalCents,
		&i.IdempotencyKey,
		&i.PaymentProvider,
		&i.PaymentStatus,
		&i.StripePaymentIntentID,
		&i.ClientSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderForUser = `-- name: GetOrderForUser :one
SELECT id, user_id, cart_id, status, currency, subtotal_cents, total_cents,
       idempotency_key, payment_provider, payment_status, stripe_payment_intent_id,
       client_secret, created_at, updated_at
FROM orders WHERE id = $1 AND user_id = $2
`

type GetOrderForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID string    `json:"user_id"`
}

func (q *Queries) GetOrderForUser(ctx context.Context, arg GetOrderForUserParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderForUser, arg.ID, arg.UserID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CartID,
		&i.Status,
		&i.Currency,
		&i.SubtotalCents,
		&i.TotalCents,
		&i.IdempotencyKey,
		&i.PaymentProvider,
		&i.PaymentStatus,
		&i.StripePaymentIntentID,
		&i.ClientSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOutbox = `-- name: InsertOutbox :exec
INSERT INTO outbox (aggregate_type, aggregate_id, event_type, payload, trace_parent)
VALUES ($1, $2, $3, $4, $5)
`

type InsertOutboxParams struct {
	AggregateType string          `json:"aggregate_type"`
	AggregateID   uuid.UUID       `json:"aggregate_id"`
	EventType     string          `json:"event_type"`
	Payload       json.RawMessage `json:"payload"`
	TraceParent   string          `json:"trace_parent"`
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) error {
	_, err := q.db.Exec(ctx, insertOutbox,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
		arg.TraceParent,
	)
	return err
}

const insertProcessedEvent = `-- name: InsertProcessedEvent :execrows
INSERT INTO processed_events (event_id) VALUES ($1)
ON CONFLICT (event_id) DO NOTHING
`

// webhook 幂等:首次插入 1 行;重复投递 0 行。
func (q *Queries) InsertProcessedEvent(ctx context.Context, eventID string) (int64, error) {
	result, err := q.db.Exec(ctx, insertProcessedEvent, eventID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAbandonedPendingOrders = `-- name: ListAbandonedPendingOrders :many
SELECT id FROM orders
WHERE status = 'pending'
  AND stripe_payment_intent_id IS NULL
  AND created_at < $1
ORDER BY created_at
LIMIT $2
`

type ListAbandonedPendingOrdersParams struct {
	OlderThan time.Time `json:"older_than"`
	MaxRows   int32     `json:"max_rows"`
}

// B6: orders stuck 'pending' that never received a payment intent (intent
// creation failed after the order committed) and are older than the cutoff. With
// no PI no payment can ever succeed, so a sweeper can safely cancel them and
// release any stock still held — no late-payment race.
func (q *Queries) ListAbandonedPendingOrders(ctx context.Context, arg ListAbandonedPendingOrdersParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listAbandonedPendingOrders, arg.OlderThan, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT id, order_id, variant_id, sku, name, unit_price_cents, qty, line_total_cents, created_at
FROM order_items WHERE order_id = $1 ORDER BY created_at
`

func (q *Queries) ListOrderItems(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.VariantID,
			&i.Sku,
			&i.Name,
			&i.UnitPriceCents,
			&i.Qty,
			&i.LineTotalCents,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT o.id, o.status, o.total_cents, o.currency, o.created_at,
       COALESCE(SUM(oi.qty), 0)::bigint AS item_count
FROM orders o
LEFT JOIN order_items oi ON oi.order_id = o.id
WHERE o.user_id = $1
GROUP BY o.id
ORDER BY o.created_at DESC
LIMIT $2 OFFSET $3
`

type ListOrdersByUserParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListOrdersByUserRow struct {
	ID         uuid.UUID `json:"id"`
	Status     string    `json:"status"`
	TotalCents int64     `json:"total_cents"`
	Currency   string    `json:"currency"`
	CreatedAt  time.Time `json:"created_at"`
	ItemCount  int64     `json:"item_count"`
}

func (q *Queries) ListOrdersByUser(ctx context.Context, arg ListOrdersByUserParams) ([]ListOrdersByUserRow, error) {
	rows, err := q.db.Query(ctx, listOrdersByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdersByUserRow
	for rows.Next() {
		var i ListOrdersByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.TotalCents,
			&i.Currency,
			&i.CreatedAt,
			&i.ItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOrderFailed = `-- name: MarkOrderFailed :execrows
UPDATE orders SET status = $2, payment_status = 'failed', updated_at = now()
WHERE id = $1 AND status = 'pending'
`

type MarkOrderFailedParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) MarkOrderFailed(ctx context.Context, arg MarkOrderFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOrderFailed, arg.ID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markOrderPaid = `-- name: MarkOrderPaid :execrows
UPDATE orders SET status = 'paid', payment_status = 'succeeded', updated_at = now()
WHERE id = $1 AND status = 'pending'
`

// 仅 pending → paid(幂等:重复 webhook 第二次受影响 0 行)。
func (q *Queries) MarkOrderPaid(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markOrderPaid, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setOrderPaymentIntent = `-- name: SetOrderPaymentIntent :exec
UPDATE orders SET stripe_payment_intent_id = $2, client_secret = $3, updated_at = now()
WHERE id = $1
`

type SetOrderPaymentIntentParams struct {
	ID                    uuid.UUID `json:"id"`
	StripePaymentIntentID *string   `json:"stripe_payment_intent_id"`
	ClientSecret          *string   `json:"client_secret"`
}

func (q *Queries) SetOrderPaymentIntent(ctx context.Context, arg SetOrderPaymentIntentParams) error {
	_, err := q.db.Exec(ctx, setOrderPaymentIntent, arg.ID, arg.StripePaymentIntentID, arg.ClientSecret)
	return err
}
