// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package eventsdb

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const countDeadLetters = `-- name: CountDeadLetters :one
SELECT COUNT(*)::bigint FROM dead_letters
`

func (q *Queries) CountDeadLetters(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDeadLetters)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const insertDeadLetter = `-- name: InsertDeadLetter :exec
INSERT INTO dead_letters (consumer, event_id, subject, event_type, payload, error, attempts)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertDeadLetterParams struct {
	Consumer  string          `json:"consumer"`
	EventID   string          `json:"event_id"`
	Subject   string          `json:"subject"`
	EventType string          `json:"event_type"`
	Payload   json.RawMessage `json:"payload"`
	Error     string          `json:"error"`
	Attempts  int32           `json:"attempts"`
}

func (q *Queries) InsertDeadLetter(ctx context.Context, arg InsertDeadLetterParams) error {
	_, err := q.db.Exec(ctx, insertDeadLetter,
		arg.Consumer,
		arg.EventID,
		arg.Subject,
		arg.EventType,
		arg.Payload,
		arg.Error,
		arg.Attempts,
	)
	return err
}

const isEventConsumed = `-- name: IsEventConsumed :one
SELECT EXISTS(
    SELECT 1 FROM consumed_events WHERE consumer = $1 AND event_id = $2
)::bool
`

type IsEventConsumedParams struct {
	Consumer string `json:"consumer"`
	EventID  string `json:"event_id"`
}

// 去重门:该 (consumer,event_id) 是否已消费。处理前查,已消费则跳过。
func (q *Queries) IsEventConsumed(ctx context.Context, arg IsEventConsumedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isEventConsumed, arg.Consumer, arg.EventID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listDeadLetters = `-- name: ListDeadLetters :many
SELECT id, consumer, event_id, subject, event_type, payload, error, attempts, created_at
FROM dead_letters
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListDeadLettersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListDeadLetters(ctx context.Context, arg ListDeadLettersParams) ([]DeadLetter, error) {
	rows, err := q.db.Query(ctx, listDeadLetters, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeadLetter
	for rows.Next() {
		var i DeadLetter
		if err := rows.Scan(
			&i.ID,
			&i.Consumer,
			&i.EventID,
			&i.Subject,
			&i.EventType,
			&i.Payload,
			&i.Error,
			&i.Attempts,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnpublishedOutbox = `-- name: ListUnpublishedOutbox :many

SELECT id, aggregate_type, aggregate_id, event_type, payload, trace_parent, created_at
FROM outbox
WHERE published_at IS NULL
ORDER BY id
LIMIT $1
`

type ListUnpublishedOutboxRow struct {
	ID            int64           `json:"id"`
	AggregateType string          `json:"aggregate_type"`
	AggregateID   uuid.UUID       `json:"aggregate_id"`
	EventType     string          `json:"event_type"`
	Payload       json.RawMessage `json:"payload"`
	TraceParent   string          `json:"trace_parent"`
	CreatedAt     time.Time       `json:"created_at"`
}

// 事件基础设施查询(outbox relay 发布 + 消费者幂等去重 + DLQ)。
// relay 轮询:按 id 顺序取未发布的 outbox 行(FIFO)。
func (q *Queries) ListUnpublishedOutbox(ctx context.Context, limit int32) ([]ListUnpublishedOutboxRow, error) {
	rows, err := q.db.Query(ctx, listUnpublishedOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnpublishedOutboxRow
	for rows.Next() {
		var i ListUnpublishedOutboxRow
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.TraceParent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEventConsumed = `-- name: MarkEventConsumed :execrows
INSERT INTO consumed_events (consumer, event_id) VALUES ($1, $2)
ON CONFLICT (consumer, event_id) DO NOTHING
`

type MarkEventConsumedParams struct {
	Consumer string `json:"consumer"`
	EventID  string `json:"event_id"`
}

// 处理成功/进 DLQ 后落标(幂等):首次写 1 行;重复写 0 行。
func (q *Queries) MarkEventConsumed(ctx context.Context, arg MarkEventConsumedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markEventConsumed, arg.Consumer, arg.EventID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markOutboxPublished = `-- name: MarkOutboxPublished :exec
UPDATE outbox SET published_at = now() WHERE id = $1
`

func (q *Queries) MarkOutboxPublished(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markOutboxPublished, id)
	return err
}
